- bank_tiles.h
- fasm-plugin/Makefile
- fasm-plugin/fasm.cc
- xdc-plugin/BANK.v
- xdc-plugin/Makefile
- xdc-plugin/xdc.cc
The initial versions of the plugins are capable of reading an XDC file with the INTERNAL_VREF settings and generating a FASM file with the features that we currently have in our database that are related to the VREF settings per bank.
This plugin operates on the existing design and modifies its structure based on the content of the XDC (Xilinx Design Constraints) file.
Since the XDC file consists of Tcl commands it is read using Yosys's tcl command and processed by the new XDC commands imported to the Tcl interpreter.
To use the plugins which are compiled as shared libraries they need to be copied to `share/yosys/plugins/` directory and later on in the yosys script they should be loaded with the `plugin command`
The information about available IO banks for a specific part and what tiles …
> XDC and FASM Yosys plugins for INTERNAL_VREF support.

- xdc-plugin/xdc.cc
This PR annotates the design read from verilog with IOSTANDARD, SLEW, DRIVE and IN_TERM parameters read from XDC.
Currently only single bit ports are supported.
However we need to handle bus ports for Litex.
> Annotate verilog with XDC parameters.

- Makefile
- fasm-plugin/Makefile
- xdc-plugin/Makefile
> Change default target to avoid installation.

- xdc-plugin/tests/Makefile
- xdc-plugin/tests/package_pins/package_pins.tcl
- xdc-plugin/tests/package_pins/package_pins.v
- xdc-plugin/tests/package_pins/package_pins.xdc
- xdc-plugin/tests/package_pins/package_pins_golden.json
- xdc-plugin/xdc.cc
This PR adds the `PACKAGE_PIN` property support to the XDC plugin. Solves #31.
> XDC: Add PACKAGE_PIN property support

- Makefile
- get_count-plugin/Makefile
- get_count-plugin/get_count.cc
- get_count-plugin/tests/Makefile
- get_count-plugin/tests/simple/Makefile
- get_count-plugin/tests/simple/design.v
- get_count-plugin/tests/simple/script.tcl
This is a plugin that allows to return to the TCL interpreter number of selected modules, cells or wires. It is used in synthesis script for QuickLogic FPGAs.
> Cell counting plugin

- sdc-plugin/sdc_writer.cc
- sdc-plugin/sdc_writer.h
- sdc-plugin/set_false_path.cc
- sdc-plugin/tests/set_false_path/set_false_path.golden.sdc
- sdc-plugin/tests/set_false_path/set_false_path.tcl
The XDC file generated for the base litex design contains the following command:
```
set_false_path -quiet -through [get_nets -hierarchical -filter {mr_ff == TRUE}]
```
While we do have the `set_false_path` command already implemented we are missing the `through` switch.
This PR addressed that.
> Add -through switch to set_false_path command

- sdc-plugin/sdc.cc
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/get_clocks/get_clocks.golden.txt
- sdc-plugin/tests/get_clocks/get_clocks.input.sdc
- sdc-plugin/tests/get_clocks/get_clocks.tcl
- sdc-plugin/tests/get_clocks/get_clocks.v
This PR depends on #51 
It add the `-of` and `-include_generated_clocks` switches to `get_clocks` command since they are used in the linux litex SDC.
> Add -of switch and -include_generated_clocks to get_clocks command

- sdc-plugin/propagation.cc
- sdc-plugin/propagation.h
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/pll/pll.v
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.golden.sdc
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.input.sdc
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.tcl
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.v
This PR fixes the problem found in https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1753#issuecomment-733165240
If the wire on the clock divider output doesn't drive any cells it won't be added to the list of generated clocks.
> SDC: Skip adding clocks on dangling wires

- sdc-plugin/clocks.cc
- sdc-plugin/clocks.h
- sdc-plugin/propagation.cc
- sdc-plugin/propagation.h
- sdc-plugin/sdc.cc
- sdc-plugin/sdc_writer.cc
- sdc-plugin/tests/counter/counter.golden.sdc
- sdc-plugin/tests/counter/counter.golden.txt
- sdc-plugin/tests/counter/counter.tcl
- sdc-plugin/tests/counter2/counter.txt
- sdc-plugin/tests/counter2/counter2.golden.sdc
- sdc-plugin/tests/counter2/counter2.golden.txt
- sdc-plugin/tests/get_clocks/get_clocks.golden.txt
- sdc-plugin/tests/get_clocks/get_clocks.v
- sdc-plugin/tests/pll/pll.golden.sdc
- sdc-plugin/tests/pll_approx_equal/pll_approx_equal.golden.sdc
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.golden.sdc
- sdc-plugin/tests/pll_div/pll_div.golden.sdc
- sdc-plugin/tests/pll_fbout_phase/pll_fbout_phase.golden.sdc
This PR aims at solving issue #53.
Added a distinction between three types of clocks:
* explicit - added with `create_clock` command 
* generated - propagated clocks that have different clock parameters than the master clock (like PLLs or MMCMs)
* propagated clocks - clock wires with the same clock parameters as their master clock
> Clock propagation enhancement

- sdc-plugin/propagation.cc
This PR basically adds a TODO comment to remind us to get rid of it once issue https://github.com/SymbiFlow/yosys-symbiflow-plugins/issues/59 is fixed.
> SDC: Add TODO comment to remove dangling wire check

- bank_tiles.h
- sdc-plugin/sdc.cc
* add missing include in xdc plug-in
* make get_bank_tiles() an inline function to avoid duplicate
symbols if all plugins are linked together.
> Fix compilation

- sdc-plugin/sdc.cc
- sdc-plugin/sdc_writer.cc
- sdc-plugin/sdc_writer.h
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/pll_propagated/pll_propagated.golden.sdc
- sdc-plugin/tests/pll_propagated/pll_propagated.input.sdc
- sdc-plugin/tests/pll_propagated/pll_propagated.tcl
- sdc-plugin/tests/pll_propagated/pll_propagated.v
This PR solves issue #64 by adding the `-include_propagated_clocks` switch which adds all propagated clocks to the written SDC.
> SDC: Add include_propagated_clocks switch

- Makefile_plugin.common
- xdc-plugin/Makefile
The install utility will set the proper permissions for the file
at hand while cp just sets the permissions at the destination
it gets from the original file - which might be totally wrong
depending on the users' umask.
> Use install instead of cp for install purposes.

- design_introspection-plugin/tests/get_cells/get_cells.tcl
- design_introspection-plugin/tests/get_nets/get_nets.tcl
- design_introspection-plugin/tests/get_pins/get_pins.tcl
- design_introspection-plugin/tests/get_ports/get_ports.tcl
- get_count-plugin/tests/simple/simple.tcl
- sdc-plugin/tests/set_clock_groups/set_clock_groups.tcl
- selection-plugin/tests/counter/counter.tcl
- xdc-plugin/tests/minilitex_ddr_arty/minilitex_ddr_arty.tcl
This makes all tests use the same concept for accessing the
test verilog file in question. It also makes it possible to
run tests from different directories if only DESIGN_TOP is set
correctly.
In one place, a filename is resolved intended relative to the script,
but currently requires the script to be executed in the same
directory; make that location independent by reading it
relative to [file dirname [info script]]
> In tests: Use $::env(DESIGN_TOP) where it isn't already.

- Makefile_test.common
- design_introspection-plugin/tests/get_cells/get_cells.tcl
- design_introspection-plugin/tests/get_nets/get_nets.tcl
- design_introspection-plugin/tests/get_pins/get_pins.tcl
- design_introspection-plugin/tests/get_ports/get_ports.tcl
- params-plugin/tests/pll/pll.tcl
- sdc-plugin/tests/counter/counter.tcl
- sdc-plugin/tests/counter2/counter2.tcl
- sdc-plugin/tests/get_clocks/get_clocks.tcl
- sdc-plugin/tests/period_check/period_check.tcl
- sdc-plugin/tests/period_format_check/period_format_check.tcl
- sdc-plugin/tests/pll/pll.tcl
- sdc-plugin/tests/pll_approx_equal/pll_approx_equal.tcl
- sdc-plugin/tests/pll_dangling_wires/pll_dangling_wires.tcl
- sdc-plugin/tests/pll_div/pll_div.tcl
- sdc-plugin/tests/pll_fbout_phase/pll_fbout_phase.tcl
- sdc-plugin/tests/pll_propagated/pll_propagated.tcl
- sdc-plugin/tests/restore_from_json/restore_from_json.tcl
- sdc-plugin/tests/set_clock_groups/set_clock_groups.tcl
- sdc-plugin/tests/set_false_path/set_false_path.tcl
- sdc-plugin/tests/set_max_delay/set_max_delay.tcl
- sdc-plugin/tests/waveform_check/waveform_check.tcl
- selection-plugin/tests/counter/counter.tcl
- test-utils/test-utils.tcl
- xdc-plugin/tests/counter/counter.tcl
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.tcl
- xdc-plugin/tests/minilitex_ddr_arty/minilitex_ddr_arty.tcl
- xdc-plugin/tests/package_pins/package_pins.tcl
- xdc-plugin/tests/port_indexes/port_indexes.tcl
In preparation for CI's and other test environments in which
the test outputs should be stored out-of-tree.
The new file test-utils.tcl provides a function that determines
the test output path (currently just by concatenating the filename
with a path from the environment). The Makefile_test.common sources
this utils file and the corresponding test file.
Since this adds a convenient test-utils.tcl file, this might also
be useful to put some testing boilerplate functionality there in
the future.
> Make output path for test outputs configurable.

- .editorconfig
Setting the indentation for tcl and cc to 4 characters which
is mostly what is happening in this repository. There are
a few tabs here and there, but they will vanish with changes
happening there
The .editorconfig file is supported by a vast number of IDEs and
editors, so hopefully this will make it simpler for would-be
contributors.
> Add .editorconfig, to help contributors honor coding style.

- params-plugin/tests/pll/techmaps/cells_map.v
Newer Yosys rejects the broken way to have multiple localparams in branches of the generate statements.
> Fix non-constant assignments to localparams.

- Makefile
- Makefile_plugin.common
- ql-qlf-k4n8-plugin/Makefile
- ql-qlf-k4n8-plugin/cells_sim.v
- ql-qlf-k4n8-plugin/qlf_k4n8_arith_map.v
- ql-qlf-k4n8-plugin/qlf_k4n8_cells_sim.v
- ql-qlf-k4n8-plugin/synth_quicklogic.cc
- ql-qlf-k4n8-plugin/tests/Makefile
- ql-qlf-k4n8-plugin/tests/dffs/dffs.tcl
- ql-qlf-k4n8-plugin/tests/dffs/dffs.v
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.tcl
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.v
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.ys
- ql-qlf-k4n8-plugin/tests/latches/latches.tcl
- ql-qlf-k4n8-plugin/tests/latches/latches.v
- ql-qlf-k4n8-plugin/tests/logic/logic.tcl
- ql-qlf-k4n8-plugin/tests/logic/logic.v
- ql-qlf-k4n8-plugin/tests/logic/logic.ys
- ql-qlf-k4n8-plugin/tests/ql_qlf_k4n8/run-test.sh
- ql-qlf-k4n8-plugin/tests/soft_adder/soft_adder.tcl
- ql-qlf-k4n8-plugin/tests/soft_adder/soft_adder.v
This PR adds qlf_k4n8 synthesis flow (as discussed in https://github.com/SymbiFlow/yosys/pull/92)
This plugin is required by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2036
> Add qlf_k4n8 plugin

- ql-qlf-k4n8-plugin/synth_quicklogic.cc
- ql-qlf-k4n8-plugin/tests/Makefile
- ql-qlf-k4n8-plugin/tests/dffs/dffs.tcl
- ql-qlf-k4n8-plugin/tests/dffs/dffs.v
This PR fixes the issue of the flow inferring unsupported `$sdff` flip-flops by adding the `dfflegalize` pass.
> Fix incorrect behavior of QuickLogic qlf_k4n8 synthesis flow

- ql-qlf-k4n8-plugin/Makefile
- ql-qlf-k4n8-plugin/qlf_k4n8_cells_sim.v
- ql-qlf-k4n8-plugin/qlf_k4n8_ffs_map.v
- ql-qlf-k4n8-plugin/synth_quicklogic.cc
- ql-qlf-k4n8-plugin/tests/Makefile
- ql-qlf-k4n8-plugin/tests/dffs/dffs.tcl
- ql-qlf-k4n8-plugin/tests/dffs/dffs.v
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.tcl
- ql-qlf-k4n8-plugin/tests/shreg/shreg.tcl
- ql-qlf-k4n8-plugin/tests/shreg/shreg.v
This PR adds support for local flip-flop resets for the QuickLogic qlf_k4n8 architecture. It also adds an additional flip-flop type for a shift register as well as shift register inference. Tests have been updated accordingly.
> Flip-flop reset support for QuickLogic qlf_k4n8

- Makefile
- Makefile_plugin.common
- Makefile_test.common
- ql-iob-plugin/tests/Makefile
- ql-iob-plugin/tests/ckpad/Makefile
- ql-iob-plugin/tests/sdiomux/Makefile
Don't clutter the output with entering/leaving directory messages or spurious warnings from tools. Have one line output per test if possible.
Warnings and other yosys logs end up in the test-specific logfile.
The test results are clearly marked and highlighted as passing/failing.
> Reduce visual noise when running tests.

- xdc-plugin/tests/compare_output_json.py
- xdc-plugin/tests/io_loc_pairs/cells_xtra.v
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.golden.json
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.tcl
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.v
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.xdc
- xdc-plugin/xdc.cc
The GTPE2_CHANNEL does not have intermediate buffers to the IOPADs. Therefore, it is necessary to allow it to have IO_LOC_PAIRS attributes to generate correct placement constraints based on the IO signals locations.
> xdc: allow GTPE2_CHANNEL to have IO_LOC_PAIRS

- ql-qlf-k4n8-plugin/tests/dffs/dffs.tcl
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.tcl
- ql-qlf-k4n8-plugin/tests/latches/latches.tcl
- ql-qlf-k4n8-plugin/tests/logic/logic.tcl
- ql-qlf-k4n8-plugin/tests/shreg/shreg.tcl
- ql-qlf-k4n8-plugin/tests/soft_adder/soft_adder.tcl
The line that is loading the plug-in is meant to skip attempting
loading a plugin with a particular name if the symbol we're interested
in is already there.
So in the ql-qlf-k4n8 case, we have to test for synth_quicklogic:
```diff
-if { [info procs ql-qlf-k4n8] == {} } { plugin -i ql-qlf-k4n8 }
+if { [info procs synth_quicklogic] == {} } { plugin -i ql-qlf-k4n8 }
```
(reason for all that: this allows to statically link the plugins
and have these scripts work idempotently).
For loading the test-related *.v files: use `$::env(DESIGN_TOP).v`
instead of the direct name. That allows it to run independently
from where the tests are invoked, as the test-driver can set the
environment variable to the fully qualified path.
> Fix loading of ql-qlf-k4n8 plugin in tests; use canonical test.v name

- ql-qlf-k4n8-plugin/qlf_k4n8_ffs_map.v
- ql-qlf-k4n8-plugin/synth_quicklogic.cc
- ql-qlf-k4n8-plugin/tests/dffs/dffs.v
- ql-qlf-k4n8-plugin/tests/iob_no_flatten/iob_no_flatten.v
This PR fixes the order in which the two mentioned passes are invoked. It also fixes a bug in the shift register techmap.
> Fix for incorrect 'techmap' and 'dfflegalize' pass ordering

- ql-qlf-plugin/synth_quicklogic.cc
dfflegalize may generated additional dffs that need to be mapped. Hence moving the techmap after dffleagalize.
> move the ff techmap step after dfflegalize

- xdc-plugin/tests/Makefile
- xdc-plugin/tests/counter-dict/counter-dict.golden.json
- xdc-plugin/tests/counter-dict/counter-dict.tcl
- xdc-plugin/tests/counter-dict/counter-dict.v
- xdc-plugin/tests/counter-dict/counter-dict.xdc
- xdc-plugin/xdc.cc
This change adds support to load pin properties from single-line
dictionaries.
Implementation and test-case were added. Test case mirrors `counter` case but with `-dict` properties (mixed usage in same file).
Fixes #32
Signed-off-by: Carlos de Paula <me@carlosedp.com>
> XDC: Support loading properties from dictionaries

- .github/workflows/setup.sh
As of version `20210510.0` of GH actions Ubuntu 20.04 image GCC 11 was added. Parts of the GCC 11 library used by clang (not sure how) make Yosys build fail. ~This PR solves that by uninstalling GCC 11 prior to Yosys compilation.~
This PR makes Yosys being built by GCC (version 9 in this case) instead of clang.
> Fix CI failures

- ql-qlf-plugin/ql-qlf-k6n10/qlf_k6n10_cells_sim.v
- ql-qlf-plugin/ql-qlf-k6n10/qlf_k6n10_ffs_map.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/dffs/dffs.tcl
- ql-qlf-plugin/tests/dffs/dffs.v
- ql-qlf-plugin/tests/latches/latches.tcl
- ql-qlf-plugin/tests/latches/latches.v
Following [ql_dsp & ff PR](https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/112), this PR adds support for FFs in qlf_k6n10 device:
- FF with enable pin, async set and reset.
- Latch with async set & reset.
I will enable Bram testcase, and add QL_DSP support in two follow up PRs.
> Add ff support to qlf_k6n10 device

- ql-qlf-plugin/ql_dsp.pmg
This PR removes subpattern matching for dff cells performed during ql_dsp pass.
Currently QL_DSP performs strictly combinatorial operations, and ff absorption in some testcases breaks the synthesis.
dff subpattern have been commented out instead of being removed because we will use them in the future when QL_DSP will be converted into a MAC Unit.
Signed-off-by: Samy <samy.charas@cpe.fr>
> Removing dff absorption operated by ql_dsp

- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-edif.cc
- ql-qlf-plugin/synth_quicklogic.cc
This PR adds a modified version of the yosys EDIF backend, which does expose the cell libraries' wide ports as multiple single-bit instead of arrays of multiple bits:
Before:
```
(cell adder
(cellType GENERIC)
(view VIEW_NETLIST
(viewType NETLIST)
(interface
(port (array (rename A "A(3:0)") 4) (direction INPUT))
(port (array (rename B "B(3:0)") 4) (direction INPUT))
(port (array (rename S "S(4:0)") 5) (direction OUTPUT))
)
)
)
```
After:
```
(cell adder
(cellType GENERIC)
(view VIEW_NETLIST
(viewType NETLIST)
(interface
(port A_0 (direction INPUT))
(port A_1 (direction INPUT))
(port A_2 (direction INPUT))
(port A_3 (direction INPUT))
(port B_0 (direction INPUT))
(port B_1 (direction INPUT))
(port B_2 (direction INPUT))
(port B_3 …
```
> ql: add custom edif backend

- xdc-plugin/tests/Makefile
- xdc-plugin/tests/package_pins-dict-space/package_pins-dict-space.golden.json
- xdc-plugin/tests/package_pins-dict-space/package_pins-dict-space.tcl
- xdc-plugin/tests/package_pins-dict-space/package_pins-dict-space.v
- xdc-plugin/tests/package_pins-dict-space/package_pins-dict-space.xdc
- xdc-plugin/xdc.cc
This PR fixes issue [#160](https://github.com/SymbiFlow/symbiflow-examples/issues/160) from symbiflow-examples by allowing multiple spaces to be placed between the pin name and IOSTANDARD in XDC dictionary parameters.
> Fix xdc parser to ignore multiple spaces

- README.md
- ql-qlf-plugin/qlf_k6n10/arith_map.v
- ql-qlf-plugin/qlf_k6n10/cells_sim.v
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
This PR modifies adders mapping for the qlf_k6n10 device.
The carry chain input is now longer directly connected to the first adder in chain CIN, but is generated using an intermediate adder.
This PR also reference ql_dsp function as part of the ql-qlf plugin in the main readme, and fix a typo qlf_k6n10 cells sim file.
> Fix adder mapping

- ql-qlf-plugin/pp3/brams_map.v
- ql-qlf-plugin/synth_quicklogic.cc
This PR fixes some incorrect wire connections (assignments) in QuickLogic PP3 BRAM techmaps so that Yosys no longer emits warnings for them.
It also modifies reading library cells in `synth_quicklogic` to use the `-nomem2reg` switch. This causes Yosys not to emit yet more warnings. (Even though we use `read_verilog` with `-lib` which should discard module content Yosys seems to still do mem2reg before unless told not to).
> Fix QuickLogic PP3 BRAM techmap warnings

- .github/workflows/build-and-test.sh
- Makefile
- Makefile_plugin.common
- Makefile_test.common
This PR adds the way to manually specify path to Yosys installation via the `YOSYS_PATH` make variable. To do that one would simple run for example:
```
make plugins YOSYS_PATH=/opt/yosys
```
> Add YOSYS_PATH to the makefile

- Makefile
This PR adds optional inclusion of the makefile from Conda env so that the plugins can be built and installed outside of it.
> Optional Conda make-env

- uhdm-plugin/UhdmAst.cc
This fixes missing ``is_reg`` attribute in custom wires for enums.
> UHDM-plugin: fix missing is_reg attribute for enums

- .github/workflows/ci.yml
- Makefile_plugin.common
- ql-qlf-plugin/synth_quicklogic.cc
This PR adds the possibility to override the `synth_quicklogic` pass name when building the plugin.
The pass name can be overriden by setting an extra flag as follows:
```
make EXTRA_FLAGS="-DPASS_NAME=new_name"
```
> ql-qlf: add possibility to override synth pass name through define

- uhdm-plugin/Makefile
On some system, Surelog libraries are installed in ``lib64`` folder.
This PR adds this path to ``LDFLAGS``.
> uhdm-plugin: look also at lib64 folder for libraries

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
- uhdm-plugin/UhdmAstAntmicro.cc
- uhdm-plugin/UhdmAstUpstream.cc
This PR adapts enums in structs to have same syntax as mainline yosys and adds support for wires with custom type and multiple ranges.
> uhdm-plugin: add support for wires with custom type and multiple ranges

- xdc-plugin/tests/Makefile
- xdc-plugin/tests/non_zero_port_indexes/non_zero_port_indexes.golden.json
- xdc-plugin/tests/non_zero_port_indexes/non_zero_port_indexes.tcl
- xdc-plugin/tests/non_zero_port_indexes/non_zero_port_indexes.v
- xdc-plugin/tests/non_zero_port_indexes/non_zero_port_indexes.xdc
- xdc-plugin/xdc.cc
This PR fixes a bug in XDC plugin that was described in https://github.com/SymbiFlow/yosys-symbiflow-plugins/issues/144
`port_bit` returned by `extract_signal()` is the same as index of given port wire, while `chunk.offset`s are always indexed starting from 0. That causes inconsistency when ports of the module are not 0-indexed as in example:
```
module Top(
output [5:2] LED
);
```
This required correcting `port_bit` with `start_offset` of the whole port.
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> xdc: fix port numbering

- uhdm-plugin/UhdmAst.cc
This function is currently unsupported by yosys.
This PR also adds dummy check for variables inside block, but for now it is disabled until finding way how to set ``VERILOG_FRONTEND::sv_mode`` from the plugin.
> Skip $value$plusargs function

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
- uhdm-plugin/UhdmAstUpstream.cc
This PR adapts uhdm-plugin for newer Surelog version. It also changes handling of custom simplification steps to allow inject custom steps between standard yosys simplification.
Fixes: https://github.com/chipsalliance/UHDM-integration-tests/issues/547
integration PR: https://github.com/antmicro/yosys-uhdm-plugin-integration/pull/222
> uhdm-plugin: adapt for newer Surelog version

- uhdm-plugin/UhdmAst.cc
Functions can be used to calculate e.g. width of the param
> Parse vpiTaskFunc before vpiParameter

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/258
> Fail when event_control is not inside always

- uhdm-plugin/Makefile
- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/uhdmsurelogastfrontend.cc
or, in case of the enumeration, at least work-around them: Storing different values in an enum than there is available might technically be undefined, but in practice this is probably ok.
> Switch on warnings and fix them

- uhdm-plugin/UhdmAst.cc
This PR removes reverse of nodes in assignment_pattern, when position notation is used. Current Surelog already gives nodes in correct position. This change adapts to the newest Surelog.
> Fix order of nodes in assignment_pattern concat

- uhdm-plugin/UhdmAst.cc
Yosys doesn't follow id2ast and simplifies it before resolving constans (it assumes, that id2ast is already simplified).
This PR workarounds this limitation.
> Follow id2ast when resolving constants

- .github/workflows/build-and-test.sh
- .github/workflows/ci.yml
- .github/workflows/setup.sh
- uhdm-plugin/Makefile
- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
- uhdm-plugin/UhdmAstAntmicro.cc
- uhdm-plugin/uhdmastshared.h
Now we should always targeting upstream yosys and this variable is no longer needed.
Some features that are still opened as PR to mainline yosys, requires patched yosys.
After merging this PR we need to make sure all repositories using uhdm-plugin reflects this change:
> Remove BUILD_UPSTREAM variable

- uhdm-plugin/UhdmAst.cc
Not flattened nodes still needs to be reversed to get correct order.
> Don't reverse only flattened nodes

- uhdm-plugin/UhdmAst.cc
This PR adapts to the newest version of Surelog. Now parameters can have value even when they have set vpiTypespec.
> Always visit parameter value

- uhdm-plugin/UhdmAst.cc
The code is already moved to use AstNode and calculate proper range.
> uhdm-plugin: remove unneeded checks

- uhdm-plugin/UhdmAstUpstream.cc
This results in duplicate-symbol link errors when linking the uhdm module
statically to yosys.
Signed-off-by: Henner Zeller <hzeller@google.com>
> Make const2ast() static, as there is already the same symbol in Yosys.

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
- uhdm-plugin/UhdmAstUpstream.cc
Global initialization in c++ results in undefined initialization
sequences. In particular when the uhdm-plugin is linked statically
to yosys, this results in a crash.
Fixed by creating the constants on first use.
Signed-off-by: Henner Zeller <hzeller@google.com>
> Avoid problematic global initialization of IdStrings.

- uhdm-plugin/UhdmAst.cc
This PR fixes several cases when uhdm-plugin results in segmentation fault.
> Add several fixes for segmentation faults

- uhdm-plugin/UhdmAst.cc
This PR adds support for custom struct member with range directly in uhdm-plugin. This is pre-PR for supporting struct member with more then 2 packed ranges.
> Add support for custom struct with range directly in uhdm-plugin

- uhdm-plugin/UhdmAst.cc
This fixes sometimes wrong struct values for parameters that are used as module parameter.
> Fix wrong struct value when it is used as module parameter

- uhdm-plugin/Makefile
- uhdm-plugin/uhdmsurelogastfrontend.cc
This PR adapts includes to new version of Surelog: https://github.com/chipsalliance/Surelog/pull/2633
> Adapt to new version of Surelog

- uhdm-plugin/UhdmAst.cc
Typedef from current module can use parameter that we are trying to simplify and module parameters can't use typedefs that are declared in module. 
> Don't simplify typedef from current module in simplify parameter

- uhdm-plugin/UhdmAst.cc
It makes this test: https://github.com/chipsalliance/UHDM-integration-tests/pull/680 passed.
> Handle vpiExpr field of packed array

- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-dsp-simd.cc
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_mult/dsp_mult.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.v
This PR adds the new `ql_dsp_simd` pass to the `ql-qlf` plugin which identifies DSP cells that have identical configurations and converts them into the single destination `QL_DSP2` cell.
The process works like following: First DSP cells representing either a full of half of the physical DSP block are inferred (see https://github.com/SymbiFlow/yosys-f4pga-plugins/pull/226) or instanced manually. Next, when the `ql_dsp_simd` pass is run pairs of matching `dsp_t1_10x9x32` cells are formed and converted into `QL_DSP2` cells. Finally a techmapping pass is run with the `dsp_final_map.v` which converts all remaining `dsp_t1_10x9x32` and `dsp_t1_20x18x64` into `QL_DSP2`.
All the rules and DSP config port names are hard coded into the plugin code so any change to them must be reflected in the code …
> QuickLogic k6n10f SIMD DSP inference

- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
Signed-off-by: rakeshm <rakeshm@quicklogic.com>
Rectified issues in cells_sim.v file:
1. line 112 from assign lut5_out[0] = s0[0]; to assign lut5_out[0] = s5[0];
2. line 231 removed extra comma:  from input E, to input E
> cells_sim.v file rectified

- uhdm-plugin/UhdmAst.cc
This PR fixes size of the value when it is parsed from vpiTypespec. ``yosys`` starts counting ranges from 0, so we need to add ``1`` to get actual ``size``.
Fixes failing ``cs_registers`` test from: https://github.com/antmicro/yosys-uhdm-plugin-integration/pull/513
> Fix size of value from vpiTypespec

- Makefile
- Makefile_plugin.common
- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-dsp-macc.cc
- ql-qlf-plugin/ql-dsp-macc.pmg
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.v
This PR adds the `ql_dsp_macc` pass which infers multiply-accumulate (MACC) operations and implements them using `k6n10f` DSP blocks.
The inference supports MACC with output either from before or after the accumulator register. `k6n10f` DSP does not allow immediate accumulator load but allows for breaking the accumulation loop on demand. This feature is supported as well. 
The tests located under `ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc` show all possible variants of how a MACC operation can be expressed in Verliog for it to be inferred correctly.
The PR also includes fixes to the plugin build system so that `pmgen` is correctly used as a dependency.
> k6n10f dsp macc inference

- uhdm-plugin/UhdmAst.cc
It is already done in ``vpiTypedef`` node.
> Remove move_type_to_new_typedef from process_*_typespec

- uhdm-plugin/UhdmAst.cc
Yosys doesn't have good handling of properties yet (see YosysHQ/yosys#3223).  In the meantime, SymbiYosys with the UHDM plugin will happily prove this model "correct":
```systemverilog
module wrong(input clk);
logic data;
always_comb data <= 0;
assert property( @(posedge clk) data );
endmodule
```
The `assert property` is silently dropped from the UHDM parse tree when it's converted to AST nodes, and the user's design has a bug but passes formal.  (Changing it to a clocked immediate assertion allows the solver to find a counterexample.)
At least, emit an error for this case.  Real support for SVA assertions can hopefully be added later.
> Emit error when encountering assert/assume properties

- Makefile_test.common
- ql-qlf-plugin/qlf_k6n10f/TDP18Kx18_FIFO.v
- ql-qlf-plugin/qlf_k6n10f/brams.txt
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/bram_tdp.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/bram_tdp.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/sim/bram_tdp_tb.v
This PR adds inference mechanism as well as proper techmap for TDP RAM in 36K mode. It also adds synthesis tests for BRAM design in 4 different configurations and introduces new test case - simulation after synthesis - to verify inference mechanisms and simulation models.
It is based on and extends PR: https://github.com/SymbiFlow/yosys-f4pga-plugins/pull/235 which needs to be merged before this one. Then it must be rebased onto newest master.
> ql-qlf: qlf_k6n10f: add TDP_BRAM36 inference

- ql-qlf-plugin/ql-dsp-macc.cc
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_mult/dsp_mult.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.tcl
This PR enables equivalence checking for tests targeting `qlf_k6n10f` DSPs. It also fixes multiple important issues with techmaps and mappings done in Yosys passes.
> Equivalence checks for qlf_k6n10f DSP tests

- ql-qlf-plugin/ql-dsp-simd.cc
This PR removes `const RTLIL::IdString` class members which caused Yosys to crash when the plugin code is built into Yosys binary.
> Removed const IdString class members

- uhdm-plugin/uhdmsurelogastfrontend.cc
These parameters are set if `-parse` is passed to Surelog
> Force -parse flag for Surelog when reading Verilog directly

- ql-qlf-plugin/qlf_k6n10f/brams.txt
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/bram_sdp.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/bram_sdp.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/sim/bram_sdp_tb.v
This PR adds the inference of SDP RAM together with synthesis+simulation tests. Test cases use SDP BRAM designs in 4 configurations: 32x512, 16x1024, 8x2048, 4x4096.
Simulation models are the same as for TDP RAM because in both SDP and TDP RAM, yosys internal memory cell is mapped into TDP36 BRAM block but configured in a different way for each RAM type.
> ql-qlf: k6n10f: Add SDP RAM inference

- ql-qlf-plugin/qlf_k6n10f/brams.txt
This PR fixes a bug that is not allowing yosys to infer RAM in qlf_k6n10f device that has port width greater than 36 bits.
Removing the matching rules for `dbits` allows yosys to instantiate multiple RAM cells 'in parallel' allowing greater data port widths than the width of a single RAM cell for given device.
I also lowered the minimal required efficiency parameter for TDP variant and removed this rule entirely for SDP variant to allow inferring really small RAMs that will occupy only a small part of the actual RAM cell in hardware. 
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> ql-qlf: qlf_k6n10f: bram: modify matching rules

- systemverilog-plugin/UhdmAst.cc
This PR adds necessary changes to adapt plugin to new Surelog version, including topPackages/allPackages split in UHDM.
> Adapt UHDM plugin to new Surelog version

- .github/workflows/setup.sh
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
This PR disables check for specific LUT types and counts for one of the `ql-qlf` tests targeting the `PP3` architecture. The synthesis result seems to be not fully deterministic and varies depending on the way Yosys is built (Conda package vs. local build). In any case the equivalence check result is always positive.
> A fix for ql-qlf plugin full_adder test

- ql-qlf-plugin/pp3/cells_sim.v
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
This PR fixes the `logic_cell_macro` simulation model by removing blocking assignment and compacting the FF model into a single `assign` statement.
> Fix for PP3 logic_cell_macro model

- dsp-ff-plugin/dsp_ff.cc
- dsp-ff-plugin/tests/nexus_conn_conflict/nexus_conn_conflict.tcl
- dsp-ff-plugin/tests/nexus_conn_share/nexus_conn_share.tcl
- dsp-ff-plugin/tests/nexus_fftypes/nexus_fftypes.tcl
- dsp-ff-plugin/tests/nexus_mult/nexus_mult.tcl
- dsp-ff-plugin/tests/nexus_mult_wide/nexus_mult_wide.tcl
- dsp-ff-plugin/tests/nexus_param_conflict/nexus_param_conflict.tcl
Making the access to the dsp rules relative to DESIGN_TOP makes
it easier to invoke the TCL script from any path.
> Make access to nexus-dsp_rules.txt in tests location indpenedent.

- systemverilog-plugin/README.md
- uhdm-plugin/README.md
This adds a README to:
* The SystemVerilog plugin itself
* The dummy UHDM plugin, with a note about deprecation and a redirection
> Add READMEs for the SystemVerilog plugin

- systemverilog-plugin/uhdmsurelogastfrontend.cc
Abort execution when Surelog report error in design. Up to now, we only aborted when Surelog reported fatal error.
Ref: https://github.com/chipsalliance/f4pga-examples/issues/290
> systemverilog: abort execution when Surelog report error in design

- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmcommonfrontend.cc
- systemverilog-plugin/uhdmsurelogastfrontend.cc
This flag can be used to only check designs, but don't load them into yosys
> systemverilog: add -parse-only flag

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
This should make it easier for users to understand the issues they're getting, for example here: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/679
> systemverilog: add dedicated wildcard operator errors

- systemverilog-plugin/UhdmAst.cc
It's okay to do this but we should warn as this may cause bugs in some cases.
> systemverilog: Add warnings to post inc/dec operations

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
* Update `import_typespec` case
* Handle shortint and time typespecs
* Fix packed ranges access in nets
> Systemverilog: adapt to current Surelog

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/uhdmsurelogastfrontend.cc
Also: use instead of a comment, use [[fallthrough]] to let the
compiler know our intent (and squash warnings due to that).
> Use new Surelog/ include location.

- Makefile_plugin.common
This PR adds support for the `DESTDIR` Makefile variable which allows to override the default plugin & data installation path provided by `yosys-config`.
> Added support for overriding installation path via DESTDIR

- systemverilog-plugin/Makefile
Look for Surelog and UHDM libraries in their default installation location. This can still be overridden for an isolated installation.
Fixes #320.
> Check default UHDM install directory

- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-bram-split.cc
- ql-qlf-plugin/qlf_k6n10f/brams.txt
- ql-qlf-plugin/qlf_k6n10f/brams_final_map.v
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/bram_sdp.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/bram_sdp.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp/sim/bram_sdp_tb.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/bram_tdp.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/bram_tdp.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp/sim/bram_tdp_tb.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp_split/bram_tdp_split.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp_split/bram_tdp_split.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp_split/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_tdp_split/sim/bram_tdp_split_tb.v
This PR introduces new BRAM inference possibilities for `qlf_k6n10f` devices. Yosys is now able to use 2 halves of TDP36K modules and merge them into single TDP36K cell in final techmap step. I also added tests cover all 2x18K bram variants and extended the tests for regular TDP36K
> ql-qlf: qlf_k6n0f: TDP BRAM split mode

- Makefile_plugin.common
DESTDIR is an *additional* prefix to the installation path, not an *alternative*: https://www.gnu.org/prep/standards/html_node/DESTDIR.html
> Makefile: fix DESTDIR handling

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
This allows i.e. declaring loop variables outside of the loop statement itself.
> Fix variable creation in unnamed scope

- systemverilog-plugin/Makefile
In clang++ and g++-12, some warnings are triggered that are benign,
but would stop compilation as we compile with -Werror.
(TODO: mayabe we only enable -Werror in the CI, but are more
lenient otherwise to not have users 'discover' such things).
> Disable benign warnings.

- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-dsp-io-regs.cc
- ql-qlf-plugin/ql-dsp-macc.cc
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_mult/dsp_mult.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.tcl
This PR adds support for DSP cells:
* QL_DSP2_MULT,
* QL_DSP2_MULT_REGIN,
* QL_DSP2_MULT_REGOUT,
* QL_DSP2_MULT_REGIN_REGOUT
This was done with new custom pass that changes the cell type to intermediate type which is then mapped onto new cells in final techmap step.
@rakeshm75, @tpagarani please take a look at this and let me know if there is anything to change here.
> ql-qlf: k6n10f: Add support for new DSP cells

- systemverilog-plugin/Makefile
The build system has no direct control over the downstream compiler, so it cannot ensure that no stray warnings are produced downstream even if the upstream compilation is warning-free. Setting `-Werror` means that these harmless warnings turn into compilation errors instead, breaking downstream builds.
> fix(systemverilog): disable -Werror

- ql-qlf-plugin/ql-bram-split.cc
- ql-qlf-plugin/qlf_k6n10f/brams.txt
- ql-qlf-plugin/qlf_k6n10f/brams_final_map.v
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp_split/bram_sdp_split.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp_split/bram_sdp_split.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp_split/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_sdp_split/sim/bram_sdp_split_tb.v
This is a follow up PR to https://github.com/chipsalliance/yosys-f4pga-plugins/pull/286. It adds missing support for SDP BRAMs in split mode. @rakeshm75, @tpagarani please have a look at this.
> ql-qlf: k6n10f: Add support for SDP split BRAM

- systemverilog-plugin/uhdmsurelogastfrontend.cc
This is the option set in compiler when using `-sverilog` switch in Surelog. It affects cases when SystemVerilog files with non-`.sv` extension are parsed.
> Use fullSVMode in Surelog

- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/ffs_map.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/dffs/dffs.tcl
- ql-qlf-plugin/tests/dffs/dffs.v
This PR makes the synthesis flow for `qlf_k6n10f` infer and emit the following flip-flop and latch types:
- ~`DFF` - regular posedge D flip-flop, no set/reset~
- ~`DFFN` - regular negedge D flip-flop, no set/reset~
- `DFFSRE` - regular posedge D flip-flop, asynchronous low-active set and reset, enable input
- `DFFNSRE` - regular negedge D flip-flop, asynchronous low-active set and reset, enable input
- `SDFFSRE` - regular posedge D flip-flop, synchronous low-active set and reset, enable input
- `SDFFNSRE` - regular negedge D flip-flop, synchronous low-active set and reset, enable input
- ~`LATCH` - regular D-latch, active high gate, no set/reset~
- ~`LATCHN` - regular D-latch, active low gate, no set/reset~
- `LATCHSRE` - regular D-latch, active high gate, asynchronous low-active set and …
> Synchronous S/R flip-flop inference for QuickLogic k6n10f

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/UhdmAstUpstream.cc
- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/break_continue/break_continue.golden.out
- systemverilog-plugin/tests/break_continue/break_continue.tcl
- systemverilog-plugin/tests/break_continue/break_continue.v
The general idea is to do transformations like:
```systemverilog
for (i = 0; i < 100; i++) begin
<statements>
continue;
<statements>
end
```
to
```systemverilog
logic $continue;
for (i = 0; i < 100; i++) begin
$continue = 0;
<statements>
$continue = 1;
if (!$continue) begin
<statements>
end
end
```
and
```systemverilog
for (i = 0; i < 100; i++) begin
<statements>
break;
<statements>
end
```
to
```systemverilog
logic $continue;
logic $break;
$break = 0;
for (i = 0; i < 100; i++) begin
if (!$break) begin
$continue = 0;
<statements>
$continue = 1;
if (!$continue) begin
<statements>
end
end
end
```
`while` loops are handled differently in that instead of wrapping the body in an `if`, the break condition gets ANDed with the original loop condition.
Integration PR: …
> SystemVerilog: Support `break` and `continue`

- systemverilog-plugin/UhdmAst.cc
Use `AST_TO_UNSIGNED` for shift operations. This mimics the way Yosys creates the AST.
> SystemVerilog: Fix children handling in shift operations

- ql-qlf-plugin/ql-dsp-io-regs.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_madd/dsp_madd.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_madd/dsp_madd.v
This PR fixes the issue of incorrect DSP type inference and incorrect clock port removal. It adds a test for multiply+add mode type change.
Due to the `feedback_i` port controlling the feedback loop of the accumulator it is not possible to tell if the requested operation is MACC or MADD if the connected signal is not a constant.
> Fix k6n10f DSP type inference

- systemverilog-plugin/UhdmAst.cc
The code for handling unions has been added together with the code for
structs, however it was never called due to a missing switch entry.
Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>
> systemverilog: simplify unions

- ql-qlf-plugin/synth_quicklogic.cc
- systemverilog-plugin/UhdmAst.cc
Testing for empty strings or containers with empty() is always
the best and canonical choice.
> Use a canonical way to test for an empty string.

- ql-qlf-plugin/Makefile
- ql-qlf-plugin/ql-bram-asymmetric-wider-read.pmg
- ql-qlf-plugin/ql-bram-asymmetric-wider-write.pmg
- ql-qlf-plugin/ql-bram-asymmetric.cc
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_read/bram_asymmetric_wider_read.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_read/bram_asymmetric_wider_read.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_read/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_read/sim/bram_asymmetric_wider_read_tb.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_write/bram_asymmetric_wider_write.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_write/bram_asymmetric_wider_write.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_write/sim/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_write/sim/bram_asymmetric_wider_write_tb.v
This PR adds inference of RAMs with asymmetric port widths. A new pass `ql_bram_asymmetric` is introduced in order to recognize circuit patterns that are characteristic to asymmetric RAMs. Detected circuits are then modified and an artificial cell is placed which is then mapped into final configured TDP36K cell. I've added two sets of tests: one for designs with wider read port, and second for designs with wider write port. Each set consist of 4 designs. Those are synthesized and tested for the inference results and the post synthesis verilog file is then simulated to verify the correctness of the configuration.
> ql-qlf: k6n10f: add asymmetric RAM inference

- ql-qlf-plugin/ql-dsp-io-regs.cc
- ql-qlf-plugin/ql-dsp-macc.cc
- ql-qlf-plugin/ql-dsp-simd.cc
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_madd/dsp_madd.v
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd/dsp_simd.v
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_simd_post_synth_sim/dsp_simd_post_synth_sim.tcl
This PR adds preservation of all manually inserted `QL_DSP2` cells - their types will never get changed.
The feature is implemented by annotating inferred DSP cells with an attribute which tells the pass that changes types that the change is allowed.
> [k6n10f] Preserve manually inserted DSPs

- ql-qlf-plugin/ql-bram-asymmetric.cc
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_read/bram_asymmetric_wider_read.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/bram_asymmetric_wider_write/bram_asymmetric_wider_write.tcl
This PR fixes the inference mechanism by changing the way BRAM wires are looked up which does not trigger Yosys assertions in specific cases. Moreover, it also ensures that inferred BRAM cell names remain unique.
> Fix QuickLogic asymmetric BRAM inference

- Makefile_plugin.common
- Makefile_test.common
Instead of `which`, the suggested alternative
is `command -v`
> Fix deprecated use of `which`

- systemverilog-plugin/UhdmAst.cc
This adds support for missing typespec that is present in newest UHDM version.
It is enough to get the interface name, Yosys can then bind the correct node.
> Handle vpiInterfaceTypespec

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
Compound assignments used to be interpreted as simple assignments, like it is described in this issue: antmicro/yosys-systemverilog#1050. This was caused by the fact, that _vpiOpType_ of _assignment_ node in UHDM tree was not taken into account.
This PR introduces operation type check in the assignment node and expanding it to include operation sub-nodes in cases where it is needed.
> systemverilog: Support op type on assignment

- systemverilog-plugin/UhdmAst.cc
Binary bitwise NAND and NOR are modeled in Surelog as bitwise reduction operations with two operands, so they need to be re-interpreted as binary bitwise operations by the plugin. Basing on how many operands are present for the operation, we decide whether it should be reduction or binary bitwise NAND/NOR.
> systemverilog: Support binary bitwise NAND and NOR

- ql-qlf-plugin/ql-bram-split.cc
Currently BRAM Split pass reports an error when it encounters SDP and TDP cells next to each other. This PR ensures that SDP and TDP cells are not mixed up and it maps every pair of the same types into one TDP36K BRAM if possible.
> ql-qlf: Split BRAM into cells with equal types only

- systemverilog-plugin/UhdmAst.cc
Fixes (partially) https://github.com/antmicro/yosys-systemverilog/issues/1064.
Test: https://github.com/chipsalliance/UHDM-integration-tests/pull/698
yosys-systemverilog workflow run: https://github.com/antmicro/yosys-systemverilog/actions/runs/3477216107
> systemverilog-plugin: Remove typedef simplification

- systemverilog-plugin/UhdmAst.cc
This PR adds some features that should make comparing diffs between the plugin and the default frontend easier:
* remove additional ranges attributes that were already converted
* retrieve Verilog line and column information from UHDM
> Minimize diffs between frontends

- systemverilog-plugin/UhdmAst.cc
Solution for https://github.com/antmicro/yosys-systemverilog/issues/1184
There are parameters declared without explicit types. In this case, the type of the parameter should default to the type of the final value assigned to the parameter .
In case if the assigned value has fixed width lesser than 32 bits, it would be assumed to be 32 bits anyway.
In the issue linked above, we have a case with 3-bit wide integers, and in the AST they were assigned a 32 bit range, which is incorrect.
I've run tests here: https://github.com/antmicro/yosys-systemverilog/pull/1272
> Check for range of integer types

- systemverilog-plugin/UhdmAst.cc
Fixes antmicro/yosys-systemverilog/issues/1224.
> systemverilog: Add support for functions out of module scope

- .github/workflows/ci.yml
`ubuntu-latest` is transitioning to Ubuntu 22.04. The CI relies on packages from 20.04.
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
> CI: Explicitly use ubuntu-20.04

- systemverilog-plugin/uhdmastfrontend.cc
- systemverilog-plugin/uhdmcommonfrontend.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
`UHDM::SynthSubset` constructor has a new argument - `allowFormal`. When it is set to `true` everything behaves like before.
Commit introducing the argument:
https://github.com/chipsalliance/UHDM/commit/d78d094448bd94926644e48adea4df293b82f101
Fixes #404
This also works with previous revisions of UHDM repository due to a temporary workaround. The workaround will be safe to be reverted after fixing issues with OpenTitan builds.
yosys-systemverilog CI  (which uses older UHDM revision) results: https://github.com/antmicro/yosys-systemverilog/actions/runs/3534236958
> Adapt to new UHDM::SynthSubset constructor signature.

- .gitignore
- Makefile
- Makefile_plugin.common
- design_introspection-plugin/Makefile
- dsp-ff-plugin/Makefile
- fasm-plugin/Makefile
- integrateinv-plugin/Makefile
- params-plugin/Makefile
- ql-iob-plugin/Makefile
- ql-qlf-plugin/Makefile
- sdc-plugin/Makefile
- systemverilog-plugin/Makefile
- uhdm-plugin/Makefile
- xdc-plugin/Makefile
- Improves dependency tracking and as a result fixes rebuilds after update of Yosys or other external dependency.
- Outputs build artifacts to `$PLUGIN_DIR/build/` instead of `$PLUGIN_DIR/`.
ql-qlf-plugin has noticeably more changes than other files, but there are no (intentional) functional changes other than mentioned above. I checked only build and installation and those work fine. @mkurc-ant if you have some separate CI for this plugin please check this PR there.
CI results from yosys-systemverilog:
https://github.com/antmicro/yosys-systemverilog/actions/runs/3524421747
> Improve build system

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
Previously, the plugin would just create a node of type `AST_TCLL`, while Yosys also processes the parameters of the task, and creates `AST_IDENTIFIER` nodes accordingly, inside the `AST_TCLL`.
With this change, the plugin processes the parameters, too.
This solves the issue described here: https://github.com/antmicro/yosys-systemverilog/issues/1137
See tests here:
https://github.com/antmicro/yosys-systemverilog/pull/1293
> process task call nodes

- systemverilog-plugin/Makefile
- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAstUpstream.cc
- systemverilog-plugin/UhdmAstUpstream.h
UhdmAstUpstream.cc is currently included in the middle of UhdmAst.cc and doesn't have any includes inside, which breaks code completion/hints.
Changes made in this PR:
- Compile UhdmAstUpstream.cc as independent object
- Provide and use a header file.
yosys-systemverilog CI: https://github.com/antmicro/yosys-systemverilog/actions/runs/3548600969
> systemverilog: Make UhdmAstUpstream.cc proper compilation unit.

- systemverilog-plugin/UhdmAst.cc
This PR aims to fix (and in some cases, add) correct handling of `signed` status to variables, nets and constants.
Fixes:
* https://github.com/antmicro/yosys-systemverilog/issues/1244
* https://github.com/antmicro/yosys-systemverilog/issues/1115
* https://github.com/antmicro/yosys-systemverilog/issues/1085
* https://github.com/antmicro/yosys-systemverilog/issues/1029
> Signed vars support

- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/debug-flag/debug-flag-buf.sv
- systemverilog-plugin/tests/debug-flag/debug-flag-pkg.sv
- systemverilog-plugin/tests/debug-flag/debug-flag.tcl
- systemverilog-plugin/tests/debug-flag/debug-flag.v
- systemverilog-plugin/tests/report-flag/report-flag-buf.sv
- systemverilog-plugin/tests/report-flag/report-flag-pkg.sv
- systemverilog-plugin/tests/report-flag/report-flag.tcl
- systemverilog-plugin/tests/report-flag/report-flag.v
- systemverilog-plugin/uhdmastfrontend.cc
- systemverilog-plugin/uhdmsurelogastfrontend.cc
According to documentation comment, `SURELOG::shutdown_compiler`
releases all UHDM/VPI resources. This happened before a call to
`visit_designs`, which uses those resources. Compiler instance along
with a few other related pointers is now managed using RAII.
yosys-sytemverilog CI: https://github.com/antmicro/yosys-systemverilog/actions/runs/3577650685
New formal verification passes:
- core_net_or_var.sv
- simple_const_func_shadow.v
- simple_scopes.v
- simple_loop_var_shadow.v
- simple_case_expr_const.v
- simple_signedexpr.v
> systemverilog: use RTTI for resource management in UhdmSurelogAstFrontend

- Makefile
- systemverilog-plugin/Makefile
- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/third_party/yosys/README
- systemverilog-plugin/third_party/yosys/const2ast.cc
- systemverilog-plugin/third_party/yosys/const2ast.h
- systemverilog-plugin/uhdmastfrontend.cc
- systemverilog-plugin/uhdmastreport.cc
- systemverilog-plugin/uhdmastreport.h
- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmcommonfrontend.cc
- systemverilog-plugin/uhdmcommonfrontend.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
The code in `UhdmAstUpstream.cc` has been moved to `third_party/yosys/const2ast.cc`. It was mostly a copy of const2ast.cc from Yosys sources. Let's not mix external and our own code when not required and
keep thirdparty code in its own directory with clear source information.
Remaining code from UhdmAstUpstream.{h,cc} (enum and mkconst_real) has been moved to UhdmAst.cc. The enum has been enclosed in additional namespace to indicate that the values are extensions.
All systemverilog-plugin code has been enclosed in `systemverilog_plugin` namespace. This fixes issue with static linking mentioned in https://github.com/chipsalliance/yosys-f4pga-plugins/commit/f95e1b244cfb54b67c3c7723e35d137359b4a132#commitcomment-92399415 and will prevent symbol name collision in the future. …
> systemverilog-plugin: use dedicated namespace and move code from const2ast.cc to third_party directory.

- ql-qlf-plugin/synth_quicklogic.cc
This PR fixes issue https://github.com/chipsalliance/yosys-f4pga-plugins/issues/422.
I tested synthesis of [full adder](https://github.com/chipsalliance/yosys-f4pga-plugins/blob/main/ql-qlf-plugin/tests/full_adder/full_adder.v#L17-L26) module for `qlf_k4n8` family in 4 different variants (with and without inferring adders and writing params in blif files) and there was no significant differences between results so we can can just always write blif with params.
Signed-off-by: Pawel Czarnecki <pczarnecki@antmicro.com>
> ql-qlf: always write blif files with .param statements

- systemverilog-plugin/UhdmAst.cc
Since `vpiContAssign` node is now present in _uhdmtopModules_ and all needed info is present there, we shouldn't visit it in _uhdmallModules_, otherwise we get duplicated AST_ASSIGN nodes as the result.
> Don't visit vpiContAssign in uhdmallModules

- systemverilog-plugin/UhdmAst.cc
Fixes https://github.com/antmicro/yosys-systemverilog/issues/1051 and https://github.com/antmicro/yosys-systemverilog/issues/1108.
> systemverilog: Fix missing interface members' types

- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/formal/formal.tcl
- systemverilog-plugin/tests/formal/formal.v
- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmcommonfrontend.cc
- systemverilog-plugin/uhdmsurelogastfrontend.cc
This adds support for the `-formal` option in the plugin, setting defines in the same way as Yosys parser and passing the option to Surelog to include verification constructs in UHDM.
> Handle -formal

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
Related to https://github.com/antmicro/yosys-systemverilog/issues/1223
https://github.com/YosysHQ/yosys/blob/52d8ddee0ccde0afccbc703d673e46457f63672b/tests/asicworld/code_hdl_models_arbiter.v#L106-L107
This usage of the bit selection operator leads to calling `simplify` on the same wire multiple times.
In general we need to be able to repeat calls to `simplify` on wires but in this case calling it again results in creating redundant `AST_RANGE` nodes.
We've agreed that removing the `simplify` call is not the right solution, so I'm adding an attribute to acknowledge that a wire was already simplified.
I'm running tests here: https://github.com/antmicro/yosys-systemverilog/actions/runs/3891658163
With additional changes in the passlist for tests: …
> Do not duplicate ranges when bit selection operator is used

- environment.yml
- systemverilog-plugin/UhdmAst.cc
This is a follow-up to #436 and #438.
PR ensures compatibility with Surelog and UHDM after enum renames in https://github.com/chipsalliance/UHDM/commit/ae0a2dc4236bc1e2e389de3ccad2d99add07a3f4.
> systemverilog: Keep enums compatible with UHDM changes

- environment.yml
- systemverilog-plugin/UhdmAst.cc
This reverts commit b87faaeed7af19375020bede8a5ea72b2048591f due to introduced compatibility in Surelog and UHDM: https://github.com/chipsalliance/Surelog/commit/7ce96e1df8e8a3cf7a504707e9f81d56889452c4.
> Revert "systemverilog: Keep enum compatibility with UHDM"

- systemverilog-plugin/UhdmAst.cc
These modifications remove nodes from being visited in _uhdmallModules_, that don't change the proper performance of the plugin when skipped.
The workflow with these modifications is tested in this PR: https://github.com/antmicro/yosys-systemverilog/pull/1357.
> Do not visit unnecessary nodes in uhdmallModules

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
`final` is unsupported by Yosys and it causes a crash with an error:
```
ERROR: :0: Encountered unhandled object '' of type 'final_stmt' 
```
From now on, there will be a warning printed since this is not a statement that should break synthesis and it is used for simulation purposes only.
FYI @mglb @wsipak @mandrys
> Add 'final' to unsupported statements 

- systemverilog-plugin/UhdmAst.cc
See https://github.com/lowRISC/opentitan/blob/748b19f8aa4bcd9b7c077d37b5f042dd23e07b23/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv#L7
```
module prim_sparse_fsm_flop #(
parameter int               Width      = 1,
parameter type              StateEnumT = logic [Width-1:0],
```
The parameter is used like this:
```
input  StateEnumT state_i,
output StateEnumT state_o
```
The type parameter is not handled by the switch in the `process_object` function.
Parameters in general are replaced with proper values by Surelog, so I expect that we can just skip processing the node in the plugin.
The result I'm getting by using `read_systemverilog -debug` is:
With `Width = 1`:
```
input [0:0] state_i;
output [0:0] state_o;
```
With `Width = 8`:
```
input [7:0] state_i;
output [7:0] state_o;
```
So, from what …
> handle vpiTypeParameter

- sdc-plugin/buffers.cc
This file does compile (by accident) in most environments, but it did stop to compile in mine. I'm using latest yosys, so maybe that's the reason.
Anyway, the file uses things from the added includes, so the includes should be there.
> sdc-plugin: Add missing includes.

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
Hot-fix for: https://github.com/chipsalliance/yosys-f4pga-plugins/pull/450
Ref: https://github.com/antmicro/yosys-systemverilog/issues/1448
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4125754497/jobs/7126745238
It moves list op in set membership operator from ``process_list_op`` to ``process_case_item``.
Because ``process_list_op`` adds nodes directly to ancestor previous approach breaks processes with multiple conditions.
Ultimately I think we should refactor ``process_list_op`` to return nodes to caller instead of adding it directly as it causes a lot of confusion.
I've also added assert to ``vpiOperand`` visit in ``process_case_item`` to make sure we don't add any nodes in this visitor.
Fixing this showed that opentitan also uses identifiers as …
> systemverilog-plugin: move handle of list op to process_case_item

- systemverilog-plugin/UhdmAst.cc
This PR fixes usage of imported function that uses another, not imported, function.
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/708
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4183705520
> systemverilog-plugin: prefer full name in function calls

- systemverilog-plugin/UhdmAst.cc
This PR adds missing release handle in ``process_tf_call`` and removes accidentally added ``dumpAst``.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4192014826
> systemverilog-plugin: release vpiHandle, remove dumpAst

- systemverilog-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-systemverilog/issues/1505
Convert memories to list of registers if we are accessing slice of memory.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4204594665
UHDM-integration test: https://github.com/chipsalliance/UHDM-integration-tests/pull/711
> systemverilog-plugin: convert memory when accessing slice

- systemverilog-plugin/UhdmAst.cc
This attribute is no longer needed.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4225039576/jobs/7336777045
> systemverilog-plugin: remove force-keep attribute

- systemverilog-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-systemverilog/issues/1508
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/713
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4252472828
> systemverilog-plugin: fix wires not starting from 0

- systemverilog-plugin/UhdmAst.cc
This PR sets ``range_left``/``range_right`` before setting ``range_valid`` to prevent negative ranges in AST.
Fixes: https://github.com/antmicro/yosys-systemverilog/issues/1506
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4342540165
> systemverilog-plugin: set range before range_valid

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
CI run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4563494012
https://github.com/antmicro/yosys-systemverilog/actions/runs/4552911545
These changes are rebased on the top of https://github.com/chipsalliance/yosys-f4pga-plugins/pull/463 as we are aiming to merge these at once.
Co-authored with @mglb.
Changes:
- The private IdStrings renamed to start with $, as this is convention used in Yosys (see: [verific frontend](https://github.com/YosysHQ/yosys/blob/f35bdaa5278b408e94ac8c97a06c3f7f0fe1773a/frontends/verific/verific.cc#L196), [ID() macro](https://github.com/YosysHQ/yosys/blob/f35bdaa5278b408e94ac8c97a06c3f7f0fe1773a/kernel/yosys.h#L344)).
- IdStrings are initialized all at once on plugin registration and removed after the design is parsed. This is required because, …
> systemverilog-plugin: Fix IdString initialization and memory leaks of AstNode objects

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
Changes:
- The private IdStrings renamed to start with `$`, as this is convention used in Yosys (see: [verific frontend][verific], [ID() macro][def_id]).
- IdStrings are initialized all at once on plugin registration and removed after the design is parsed. This is required because, for some reason, Yosys can generate slightly different output depending on how much extra IdStrings are there.
This is an initial change. Expected follow up changes:
- Remove all private attributes from final AstNode tree.
- Remove existing memory leaks of AstNode objects. Otherwise IdStrings will never unregister, as they use reference counting.
- Remove `UhdmAst::XXX()` methods and use `attr_id::XXX` directly.
[verific]: https://github.com/YosysHQ/yosys/blob/f35bdaa5278b408e94ac8c97a06c3f7f0fe1773a/frontends/v …
> systemverilog-plugin: Fix IdString initialization

- systemverilog-plugin/UhdmAst.cc
This PR fixes assignments on declaration in more generic way. Assignments on declaration in genfor blocks are handled separately, so they are left intact.
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/719
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4531860494
> systemverilog-plugin: fix assignments on declaration

- systemverilog-plugin/UhdmAst.cc
This PR fixes calculation of parameter value that uses custom (limited to plugin) simplification step.
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/715
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4488207484
> systemverilog-plugin: fix calculate parameter value that requires extended simplify

- systemverilog-plugin/UhdmAst.cc
Fixes: https://github.com/chipsalliance/yosys-f4pga-plugins/issues/467
This PR adds support for custom type with multirange inside struct/union. Hierarchical (using ``dot``) access is still restricted to single range.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4477563172
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/718
> systemverilog-plugin: add support for custom type with multiranges inside struct/union

- environment.yml
Fixes: https://github.com/chipsalliance/yosys-f4pga-plugins/issues/429
> systemverilog-plugin: unlock surelog version

- systemverilog-plugin/uhdmastshared.h
The delete param.second needs the full definition of struct AstNode.
> Add missing include.

- Makefile_plugin.common
- systemverilog-plugin/Makefile
UHDM and Surelog now both provide pkg-config configuration so using that moves the repsonsibility finding the correct include paths and libs to the right place.
Fixes #472
> Systemverilog plugin: Use pkg-config to determine dependencies.

- systemverilog-plugin/uhdmsurelogastfrontend.cc
The kitchen-sink include file Surelog/surelog.h makes things look simple, but it also hides what we actually want. So apply IWYU principle and only include what we need.
This will help us long-term to tackle
https://github.com/chipsalliance/Surelog/issues/3568
> Be specific of what includes we need from surelog.

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/uhdmastshared.h
Depends on https://github.com/chipsalliance/yosys-f4pga-plugins/pull/463 and https://github.com/chipsalliance/yosys-f4pga-plugins/pull/468
When a module with `type parameter` is instantiated, Surelog replaces the paramater with proper type name.
However, if the type is not globally defined, the `typedef` for that type is missing in the parametrized module.
The plugin should copy the typedef into proper scope.
New tests:
https://github.com/chipsalliance/UHDM-integration-tests/pull/707
CI with the changes:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4618129458
CI with the changes and the new tests:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4618128622
CI with the new tests and `main` plugins:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4608 …
> Handle type parameters

- systemverilog-plugin/UhdmAst.cc
When processing a module in OT, I got this error:
```
ERROR: ERROR: Assert `!invalidvalue' failed in UhdmAst.cc:2360
```
An identifier wasn't delcared properly, so `reduceExpr` failed, and the expected error message would be:
```
rstmgr_pkg.sv:93: ERROR: Identifier `\NumTotalResets' is implicitly declared outside of a module.
```
We wouldn't see the error about undeclared identifier, because `log_assert` stops execution.
`invalidvalue` should always be `false`, so the assert isn't really wrong. However, we should not stop the execution here.
I'm changing this to a warning instead of the assert.
In case when `reduceExpr` fails, the returned object is the same as input, so we don't need to handle the return value separately.
CI run: …
> Warn about invalidvalue in reduceExpr

- systemverilog-plugin/third_party/yosys/simplify.cc
- systemverilog-plugin/third_party/yosys/simplify.h
I am working on a patch that changes yosys types that deal with sizes to be a ys_size_type typedef (needed to get ready for bigger designs).
This change here is a no-op, but it makes it possible to change things at a single place once we're ready.
> Make it easy to change the type used for sizes.

- systemverilog-plugin/UhdmAst.cc
This PR contains multiple small fixes that combined fixes size of struct that is used as I/O in module.
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/720
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4618618727
> systemverilog-plugin: fix size of struct used as I/O wire

- systemverilog-plugin/UhdmAst.cc
> systemverilog-plugin: add information about file when we can't find ancestor for tagged pattern

- systemverilog-plugin/UhdmAst.cc
Surelog reports both definition of parameter (in ``vpiParameter``) and actual value of paramter (in ``vpiParamAssign``) in ``vpiGenScope``. Previously we were skipping empty definitions of parameters, but we should actually replace this definition with value (if available).
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/722
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4730063145/jobs/8393403356
> systemverilog-plugin: replace default parameter definition in genscope

- systemverilog-plugin/UhdmAst.cc
As reported in issue https://github.com/chipsalliance/yosys-f4pga-plugins/issues/482, in cases were typedef struct parameter is used, only the value of the first struct field was added to the whole parameter value, and the rest was ignored - it was caused by the fact that the string of the struct fields were skipped when adding the values of struct, so all of them had the same name, hence they were treated as one field.
Test _yosys-systemverilog_ CI run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4743420278
Test for the plugin: https://github.com/chipsalliance/UHDM-integration-tests/pull/723
> Take name from the AST_DOT node in pattern assignment

- .github/workflows/ci.yml
- Makefile
This is a suggestion to provide a version number to the project, and use that to also tag with the same version in git.
Context:
https://github.com/chipsalliance/yosys-f4pga-plugins/issues/489
> Add version to Makefile; use that to automatically tag the release

- .github/workflows/ci.yml
- Makefile
While at it, bump the version to today as the old PR was a few days old.
> Fix typo in verision tagging CI.

- systemverilog-plugin/UhdmAst.cc
Fixes: https://github.com/chipsalliance/yosys-f4pga-plugins/issues/491
Parameter types are mostly already propagated by Surelog, we only need them to properly rename module or move typedef definition when they are in modules. This PR skips type parameters when we visit parameters defined outside of module.
This PR also fixes initialization of attributes strings when read command is called multiple times.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4786916798
> systemverilog-plugin: fix segmentation fault when parameter type is not used in module 

- systemverilog-plugin/uhdmastfrontend.cc
- systemverilog-plugin/uhdmsurelogastfrontend.cc
This commit adapts to changes introduced in: https://github.com/chipsalliance/UHDM/pull/929
yosys-systemverilog PR using this changes with newer Surelog: https://github.com/antmicro/yosys-systemverilog/pull/1685
> systemverilog-plugin: adapt visit_object calls to new UHDM api

- systemverilog-plugin/UhdmAst.cc
We no longer need to retrieve the data from the typespec, and after a recent change in Surelog, the size of the typespec would actually cause the plugin to not get the correct value from `vpiSize`.
https://github.com/antmicro/yosys-systemverilog/pull/1700
CI running here: https://github.com/antmicro/yosys-systemverilog/actions/runs/4957974151
> do not get value size of a constant from its typespec

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/uhdmastshared.h
This PR adds support for multiple variable declarations in anonymous enum definition.
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/733
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4936906195
> systemverilog-plugin: add support for multiple variables declared in anonymous enum var

- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/translate_off/translate_off.tcl
- systemverilog-plugin/tests/translate_off/translate_off.v
- systemverilog-plugin/uhdmsurelogastfrontend.cc
Always activate `-synth` option in Surelog, which makes it ignore code between `// synopsys translate_off` and `// synopsys translate_on` (and a few other similar comments).
yosys-systemverilog: https://github.com/antmicro/yosys-systemverilog/actions/runs/4959300348
> systemverilog-plugin: Enable non-synthesizable code removal in Surelog.

- systemverilog-plugin/UhdmAst.cc
Now ``vpiPackedArrayTypespec`` can contain another, named type.
> systemverilog-plugin: fix unnamed packed array

- systemverilog-plugin/UhdmAst.cc
This PR updates message about removing unused module.
Previous message could be misleading that whole module was removed, but we are removing only unelaborated (and unused) modules.
> systemverilog-plugin: update remove module message

- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/break_continue/break_continue.tcl
- systemverilog-plugin/tests/counter/counter.tcl
- systemverilog-plugin/tests/debug-flag/debug-flag.tcl
- systemverilog-plugin/tests/defaults/defaults.tcl
- systemverilog-plugin/tests/defines/defines.tcl
- systemverilog-plugin/tests/formal/formal.tcl
- systemverilog-plugin/tests/report-flag/report-flag.tcl
- systemverilog-plugin/tests/separate-compilation/separate-compilation.tcl
- systemverilog-plugin/tests/translate_off/translate_off.tcl
When running tests locally I had an issue where the tests were unexpectedly failing. This has been caused by Surelog temporary files stored in /tmp during previous tests (probably from totally different revisions).
This patch changes temporary directory to a `tmp` subdirectory in the test directory, and extends `clean` target with a command that removes them.
yosys-systemverilog workflow: https://github.com/antmicro/yosys-systemverilog/actions/runs/4981917441
> systemverilog-plugin: Remove temporary test files.

- systemverilog-plugin/UhdmAst.cc
This PR splits line and column in reported error:
currently:
```
top.sv:1215: note: When processing object of type 'operation'.
```
after this PR:
```
top.sv:12:15: note: When processing object of type 'operation'.
```
> systemverilog-plugin: split line and column in uhdmast_assert_log

- systemverilog-plugin/UhdmAst.cc
See https://github.com/chipsalliance/yosys-f4pga-plugins/issues/517
In order to allow multiranges in dot notation, it's useful to first fix the usage of `multirange_dimensions` in the plugin.
See https://github.com/YosysHQ/yosys/blob/master/frontends/ast/ast.h#L205
Currently, the plugin doesn't put proper data into the vector. For objects of type `AST_STRUCT_ITEM` it puts there only one number representing the size of the first dimension.
With these changes, the function `add_multirange_attribute` will always push even number of elements to `multirange_dimensions`, which is the way it should work. It also handles `AST_STRUCT_ITEMS` so that information about all the dimensions is included, not only the first one.
The function `expand_dot` will now allow multiple ranges, and will iterate …
> systemverilog-plugin: allow multirange access in dot access

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
This PR fixes anonymous enums when they are declared in submodule and this submodule is used multiple times with the same parameters.
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/739
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/5130641235
All unexpected failures in yosys-systemverilog run:
```
yosys:asicworld/code_hdl_models_GrayCounter.v
yosys:simple/always03.v
yosys:simple/sincos.v
yosys:asicworld/code_verilog_tutorial_fsm_full.v
yosys:simple/operators.v
```
are due to additional IdString and different optimizations applied to netlist. I've checked that AST for this tests are identical as before this PR.
> systemverilog-plugin: fix anonymous enum when declared in submodules

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/third_party/yosys/simplify.cc
This PR fixes size and access to packed array of enum.
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/732
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4935744732
> systemverilog-plugin: fix packed arrays of enums

- systemverilog-plugin/UhdmAst.cc
Ref: https://github.com/chipsalliance/yosys-f4pga-plugins/issues/524
This PR adds support for multirange in ``dot`` context (before first ``dot``).
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/740
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/5186512253/jobs/9347862380
> yosys-systemverilog: fix multirange with dot usage

- systemverilog-plugin/UhdmAst.cc
Recently, the naming of objects in `hier_path` has changed in Surelog.
See https://github.com/chipsalliance/Surelog/issues/3691.
Here's a CI run with bumped Surelog (`7689edf`), where `MemberSelectOf2DStructPackedArray` and other tests fail:
https://github.com/antmicro/yosys-systemverilog/actions/runs/5197447471
These changes fix the tests, see the CI with newer Surelog and the changes:
https://github.com/antmicro/yosys-systemverilog/actions/runs/5199424709
And also with the current Surelog submodule, the changes don't break anything, CI:
https://github.com/antmicro/yosys-systemverilog/actions/runs/5199420625
> Fix hier path processing

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/utils/memory.h
Fixes leaks and adds `unique_resource` class to make leaking from `std::vector<AST::AstNode*>` (and similar classes, but this one is used quite often) harder.
The `unique_resource` works like `unique_ptr`, but wraps object of any type (not only pointers) and uses provided Deleter functor to delete that resource when needed. Default deleter that deletes all pointers in the range is provided for any range of pointers (i.e. any type `T` where `*std::begin(t)` is a pointer when `t` is an object of that type).
The class is inspired by [`std::experimental::unique_resource`][experimental], but the API is closed to `unique_ptr`. Main differences:
- `release()` returns resource by value
- `*x` (and `x->`) returns reference to the resource, it doesn't dereference any pointers. Such behavior of this …
> Fix memory leaks detected by ASAN.

- systemverilog-plugin/UhdmAst.cc
1. This refactors `add_multirange_attribute` function.
* The purpose of the function is to put data about multiranges in `node->multirange_dimensions` vector, and as it doesn't do anything related to `node->attributes`, the name could be considered misleading. I'm renaming it to `set_multirange_dimensions` and will be happy to consider other options, too.
* There was a node duplicated and then both nodes were simplified. Now it's duplicated after simplification.
* Ideally, the function should be called only once for each node. The function will now use both `packed_ranges` and `unpacked_ranges` in a single call, so that it's easier to forbid multiple calls of the function later on. 
2. The `process_net` function has a bug which causes ranges to be duplicated. With the current solution, …
> duplicated ranges

- systemverilog-plugin/uhdmastshared.h
The class `cover` in UHDM will not compile well if the `cover` macro from yosys kernel/log.h is defined. Undef it.
> Undef a macro that clashes with a UHDM class.

- systemverilog-plugin/UhdmAst.cc
If a union type was referenced as a parameter this would fail.
> Allows Union Types in Parameter Fields
