chipsalliance/yosys-f4pga-plugins

- .travis.yml
- .travis/build-and-test.sh
- .travis/common.sh
- .travis/setup.sh
- Makefile
- fasm-plugin/Makefile
- fasm-plugin/tests/Makefile
- xdc-plugin/Makefile
- xdc-plugin/tests/Makefile
This PR adds Travis CI for testing of the plugins.
> Add Travis scripts to test the plugins 

- fasm-plugin/fasm.cc
- xdc-plugin/xdc.cc
> Remove override macros that have been removed from Yosys.

- Makefile
- selection-plugin/Makefile
- selection-plugin/selection.cc
- selection-plugin/tests/Makefile
- selection-plugin/tests/counter/counter.golden.txt
- selection-plugin/tests/counter/counter.tcl
- selection-plugin/tests/counter/counter.v
Initial version of the selection_to_tcl_list command.
> Selection plugin: Initial version of selection_to_tcl_list command

- sdc-plugin/buffers.h
This PR refactors the way the PLL params are fetched.
> SDC: Refactor PLL param getter

- sdc-plugin/Makefile
- sdc-plugin/clocks.h
- sdc-plugin/sdc.cc
- sdc-plugin/sdc_writer.cc
- sdc-plugin/sdc_writer.h
- sdc-plugin/set_false_path.cc
- sdc-plugin/set_false_path.h
- sdc-plugin/set_max_delay.cc
- sdc-plugin/set_max_delay.h
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/set_false_path/set_false_path.golden.sdc
- sdc-plugin/tests/set_false_path/set_false_path.tcl
- sdc-plugin/tests/set_false_path/set_false_path.v
- sdc-plugin/tests/set_max_delay/set_max_delay.golden.sdc
- sdc-plugin/tests/set_max_delay/set_max_delay.tcl
- sdc-plugin/tests/set_max_delay/set_max_delay.v
This PR add basic support of the set_max_delay command.
It depends on #38 with the SdcWriter class.
> SDC: Add set_max_delay command

- sdc-plugin/Makefile
- sdc-plugin/clocks.h
- sdc-plugin/sdc.cc
- sdc-plugin/sdc_writer.cc
- sdc-plugin/sdc_writer.h
- sdc-plugin/set_false_path.cc
- sdc-plugin/set_false_path.h
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/set_false_path/set_false_path.golden.sdc
- sdc-plugin/tests/set_false_path/set_false_path.tcl
- sdc-plugin/tests/set_false_path/set_false_path.v
This PR add basic support of the set_false_path command.
> SDC: Add set_false_path command

- xdc-plugin/xdc.cc
> xdc-plugin: fix missing IOBUFDS

- sdc-plugin/Makefile
- sdc-plugin/buffers.cc
- sdc-plugin/clocks.cc
- sdc-plugin/clocks.h
- sdc-plugin/propagation.h
- sdc-plugin/sdc.cc
- sdc-plugin/sdc_writer.cc
- sdc-plugin/sdc_writer.h
- sdc-plugin/set_clock_groups.cc
- sdc-plugin/set_clock_groups.h
- sdc-plugin/tests/Makefile
- sdc-plugin/tests/set_clock_groups/set_clock_groups.golden.sdc
- sdc-plugin/tests/set_clock_groups/set_clock_groups.tcl
- sdc-plugin/tests/set_clock_groups/set_clock_groups.v
This PR adds basic support for the set_clock_groups command. This is needed for issue #33.
> SDC: Add set_clock_groups command

- README.md
Addresses issue #76 by adding a list of all implemented plugins with a short summary of what each plugin does and what commands it provides.
> Add list of plugins with short description

- design_introspection-plugin/get_pins.cc
> Use more optimal call to find_last_of().

- xdc-plugin/xdc.cc
> xdc: add IBUFDS_GTE2 primitive

- xdc-plugin/tests/io_loc_pairs/cells_xtra.v
- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.v
> Fix formatting of recent verilog file changes.

- xdc-plugin/tests/io_loc_pairs/io_loc_pairs.tcl
> Refer to file location in script independent from where it runs.

- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/dffs/dffs.tcl
- ql-qlf-plugin/tests/dffs/dffs.v
> move optimization steps  after ff techmap and remove redundant opt steps

- ql-qlf-plugin/ql-qlf-k4n8/qlf_k4n8_cells_sim.v
- ql-qlf-plugin/ql-qlf-k4n8/qlf_k4n8_ffs_map.v
- ql-qlf-plugin/synth_quicklogic.cc
- ql-qlf-plugin/tests/dffs/dffs.tcl
- ql-qlf-plugin/tests/dffs/dffs.v
Rebased version of https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/107
> Add dffsr support

- README.md
- ql-qlf-plugin/synth_quicklogic.cc
Signed-off-by: Maciej Kurc <mkurc@antmicro.com>
> Adding information about quicklogic plugins to README.md

- ql-qlf-plugin/synth_quicklogic.cc
…c reset support. Also adding a condition to do ABC optimization which is done by default but can be disabled by a command-line option
> Running ABC optimization based on input option specified in command line

- ql-qlf-plugin/ql-edif.cc
This PR fixes the custom EDIF writer backend for QL. It is required that LUT INIT hex codes have length padded with the amount zeros that is corresponding to the LUT type, e.g.: LUT2 needs overall hex code of 1 digit length, LUT3 2 digits, LUT4 4 digits and so on.
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> ql: edif: add padding to LUT INITs

- ql-qlf-plugin/qlf_k4n8/ffs_map.v
- ql-qlf-plugin/tests/dffs/dffs.tcl
- ql-qlf-plugin/tests/iob_no_flatten/iob_no_flatten.tcl
Signed-off-by: rakeshm <rakeshm@quicklogic.com>
> Modified ffs map file

- ql-qlf-plugin/qlf_k4n8/arith_map.v
- ql-qlf-plugin/qlf_k6n10/arith_map.v
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
- ql-qlf-plugin/tests/full_adder/full_adder.v
> Fix issues with carry out in k4n8 and k6n10 adder techmap

- uhdm-plugin/UhdmAst.cc
> Fix assignments on declaration in functions

- uhdm-plugin/UhdmAst.cc
This PR fixes packed ranges in parameters using mainline yosys.
> Fix packed ranges in parameter

- uhdm-plugin/UhdmAst.cc
> Add support for vpiOctStrVal

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
> Add support for byte var and long int var

- uhdm-plugin/UhdmAst.cc
> Ignore just delay_control stmt

- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> add dsp blackbox support for k6n10f

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/231
> Add support for vpiImmediateCover

- uhdm-plugin/UhdmAst.cc
> Fix some cases when typespec is anonymous

- uhdm-plugin/UhdmAst.cc
> Fix missing range in int_typespec

- uhdm-plugin/UhdmAst.cc
> Visit typedefs defined in the file level

- uhdm-plugin/UhdmAst.cc
> Add support for multiple dots in fallback

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/248
> Add support for variables defined inside named blocks

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
> Add support for vpiWhile

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
> Fix variables in unnamed blocks

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/256
> Fail on unsupported vpiClockingBlock

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/253
> Add support for vpiImmediateAssume

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/257
> Fail when range is unsized

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/259
> Add usage check to readmemh

- .github/workflows/setup.sh
- uhdm-plugin/UhdmAst.cc
> Fix simplify parameter when containing custom simplification step

- uhdm-plugin/UhdmAst.cc
> Fix hier_path handling 2d array select with custom wiretype

- uhdm-plugin/UhdmAst.cc
It also fixes order of packed ranges in enum as part of struct.
> Fix access to multirange struct elem

- uhdm-plugin/UhdmAst.cc
- uhdm-plugin/UhdmAst.h
This PR splits packed_array_var and array_var. In packed_array_var we are adding ranges to the packed_ranges.
> Fix packed array var

- uhdm-plugin/UhdmAst.cc
> Add support for custom wire with dot and packed range

- uhdm-plugin/UhdmAst.cc
> Fix reference to unpacked_ranges after merge

- uhdm-plugin/UhdmAst.cc
> Always reverse concat nodes

- uhdm-plugin/UhdmAst.cc
> Fix missing stmt when while node contains block

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/358
> Add support for parameters inside function

- uhdm-plugin/uhdmsurelogastfrontend.cc
> Add check for Surelog command line args

- uhdm-plugin/UhdmAst.cc
> Fix accessing whole unpacked range, if range doesn't start from 0

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/418
> Add support for vpiBitTypespec in enum

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/421
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/422
Fixes: https://github.com/antmicro/yosys-uhdm-plugin-integration/issues/423
> Fix missing typedef node on file-level

- ql-qlf-plugin/synth_quicklogic.cc
Signed-off-by: rakeshm <rakeshm@quicklogic.com>
Disabled the sdff implementation in qlf_k6n10f device
> Modified synth_quicklogic.cc file

- uhdm-plugin/UhdmAst.cc
Fixes: https://github.com/SymbiFlow/yosys-symbiflow-plugins/issues/218
> Add support for packed struct with range

- uhdm-plugin/UhdmAst.cc
> Adapt to new version of Surelog

- uhdm-plugin/UhdmAst.cc
> Fix more then 2 packed ranges in array_net

- uhdm-plugin/UhdmAst.cc
It is needed to pass https://github.com/chipsalliance/UHDM-integration-tests/pull/673
> Handle vpiExpr field of vpiArrayVar

- uhdm-plugin/UhdmAst.cc
> Fix param with typespec and range

- ql-qlf-plugin/qlf_k6n10f/arith_map.v
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
> Fixed adder techmap to map Carry out correctly

- uhdm-plugin/UhdmAst.cc
> Fix default signed value for parameters

- uhdm-plugin/UhdmAst.cc
> Add support for vpiMinTypMaxOp

- ql-qlf-plugin/ql-dsp-simd.cc
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
This PR changes the way in which the coefficient are modelled from input ports to cell parameters
> QuickLogic k6n10f DSP FIR coeffs as params

- uhdm-plugin/UhdmAst.cc
It fixes [AssignGeneratedWireInAlways](https://github.com/chipsalliance/UHDM-integration-tests/pull/684/files#diff-72f82c5467315af03a48001b5dcf955e8357920f252194fc9c66aca4575263d3).
> Convert AST_DOT with AST_RANGE to AST_PREFIX

- Makefile_test.common
- environment.yml
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/tests/Makefile
- ql-qlf-plugin/tests/qlf_k6n10f/sim_dsp_fir/sim_dsp_fir.v
- ql-qlf-plugin/tests/qlf_k6n10f/sim_dsp_mult/sim_dsp_mult.v
- ql-qlf-plugin/tests/qlf_k6n10f/sim_dsp_mult_r/sim_dsp_mult_r.v
This PR adds behavioral model of type 1 DSP. Based on https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/226 which has to be merged first.
This is still work in progress.
> k6n10f DSP behavioral model

- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
Signed-off-by: rakeshm <rakeshm@quicklogic.com>
Rectified the cells_sim.v compile issues, modified the dsp model (dsp_t1_sim).
Rectified the dsp_map.v and dsp_final_map.v file.
> Rectified cells_sim & dsp_map files

- ql-qlf-plugin/Makefile
Adds copying BRAM simulation files along with the others.
> Added installation of k6n10f simulation models that were missing

- ql-qlf-plugin/qlf_k6n10f/arith_map.v
- ql-qlf-plugin/tests/full_adder/full_adder.tcl
-to implement last 2 bits into regular logic
> update adder techmap 

- ql-qlf-plugin/qlf_k6n10f/arith_map.v
> fix the generation of carry chain for size <=2

- systemverilog-plugin/UhdmAst.cc
Add basic handling for vpiUnionVar (most of the support is already present through vpiUnionTypespec).
> Handle vpiUnionVar

- ql-qlf-plugin/ql-dsp-macc.cc
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
- ql-qlf-plugin/qlf_k6n10f/dsp_map.v
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_macc/dsp_macc.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_mult/dsp_mult.tcl
- ql-qlf-plugin/tests/qlf_k6n10f/dsp_mult/dsp_mult.v
- ql-qlf-plugin/tests/qlf_k6n10f/sim_dsp_fir/sim_dsp_fir.v
This PR updates the simulation models plus fixes a bug around signed multiplication (test added).
> Update k6n10f DSP simulation models

- ql-qlf-plugin/ql-dsp-simd.cc
- ql-qlf-plugin/qlf_k6n10f/brams_map.v
- ql-qlf-plugin/qlf_k6n10f/cells_sim.v
- ql-qlf-plugin/qlf_k6n10f/dsp_final_map.v
This PR aggregates all parameters of DSPs and BRAMs into a single parameter named `MODE_BITS`.
> Merge k6n10f RAM and DSP parameters into MODE_BITS

- systemverilog-plugin/UhdmAst.cc
> Parse task/function definitions inside generate blocks

- .github/workflows/build-and-test.sh
- ql-qlf-plugin/ql-bram-split.cc
- ql-qlf-plugin/ql-dsp-io-regs.cc
- ql-qlf-plugin/ql-edif.cc
Check if we can force `-Werror` in CI.
Closes: #351
> Force -Werror in CI, fix various warnings

- systemverilog-plugin/UhdmAst.cc
Fixes cases where enum was limited to one bit size, even for larger declarations (reported [here](https://github.com/chipsalliance/f4pga-examples/issues/311)).
> Fix enum widths issue

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
Signed-off-by: Krzysztof Bieganski <kbieganski@antmicro.com>
> Support `longint` typespec

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/uhdmastfrontend.cc
- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmcommonfrontend.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
> Skip non-synthesizable objects

- environment.yml
> env: pin yosys version

- systemverilog-plugin/UhdmAst.cc
Signed-off-by: Rafal Kapuscik <rkapuscik@antmicro.com>
> Remove unused modules from top_nodes

- systemverilog-plugin/UhdmAst.cc
Correctly find and annotate type for signed ports.
> Support signed ports

- systemverilog-plugin/UhdmAst.cc
The problem is described here:
https://github.com/antmicro/yosys-systemverilog/issues/1043
We've observed that even though this integer is mishandled:
```
assign a = 7698294523898761276;
```
Integers written as based literal constants with the same value are processed properly:
```
assign a = 'sd7698294523898761276;
```
The solution makes use of the already existing code for the latter case, and now integers that exceed 32 bits are treated as strings, just like based literal constants.
> handle int constants wider than 32 bits

- systemverilog-plugin/UhdmAst.cc
Fixes https://github.com/chipsalliance/yosys-f4pga-plugins/issues/400
yosys-systemverilog CI results: https://github.com/antmicro/yosys-systemverilog/actions/runs/3633893748 (one new formal test passes)
New tests for the issue: https://github.com/chipsalliance/UHDM-integration-tests/pull/700
> Fix enum types other than int (default)

- systemverilog-plugin/tests/Makefile
- systemverilog-plugin/tests/defaults/defaults.tcl
- systemverilog-plugin/tests/defaults/defaults.v
- systemverilog-plugin/tests/defines/defines.tcl
- systemverilog-plugin/tests/defines/defines.v
- systemverilog-plugin/uhdmsurelogastfrontend.cc
Rebased and slightly cleaned up version of https://github.com/chipsalliance/yosys-f4pga-plugins/pull/377
> Add systemverilog_defines, systemverilog_defaults

- environment.yml
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
> submodules: Update make-env

- systemverilog-plugin/UhdmAst.cc
Fixes https://github.com/chipsalliance/yosys-f4pga-plugins/issues/414.
> Add global typedefs to scope before simplify

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/uhdmastreport.cc
UHDM now returns std::string_view for VpiName() and VpiFile(). Prepare the plug-in to deal with it.
> Prepare plug-in to be ready for UHDM string_view return values.

- systemverilog-plugin/UhdmAst.cc
Fixes https://github.com/antmicro/yosys-systemverilog/issues/1204.
Memory is now inferred correctly and produced `_gate.v` is not different for Surelog and clean Yosys.
> systemverilog: Fix memory inference

- systemverilog-plugin/UhdmAst.cc
This PR adds initial support for list op in set membership operator using low and high bound enclosed by square braces (11.4.13 Set membership operator).
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/705
yosys-systemverilog: https://github.com/antmicro/yosys-systemverilog/pull/1483
Fixes: https://github.com/antmicro/yosys-systemverilog/issues/1448
> systemverilog: add support for list op with low and high bound

- systemverilog-plugin/UhdmAst.cc
These changes add support for memories in nested genblocks, where we need to track the current scope. Before this fix, memories with same names but in different scopes (inside and outside a genblock) were not distinguished in `check_memories` that is called to add `force_convert` attribute when we need to convert a memory into an array.
This issue was spotted when parsing OpenTitan design, after getting the following error:
```
ERROR: Assert `!memories.count(node->str)' failed in /yosys-systemverilog/yosys-f4pga-plugins/systemverilog-plugin/UhdmAst.cc:419.
```
Here is a test for the fix: https://github.com/chipsalliance/UHDM-integration-tests/pull/712,
and the PR with test workflow: https://github.com/antmicro/yosys-systemverilog/pull/1528.
> Memory in nested genblocks

- systemverilog-plugin/UhdmAst.cc
This PR updates how we are processing parameters to match it with yosys. It also removes some of no-longer-needed code.
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4355510639
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/717
> systemverilog-plugin: update module parameters processing

- systemverilog-plugin/UhdmAst.cc
Consider this example:
```
localparam int StateWidth = 9;
typedef enum logic [StateWidth-1:0] {
StActive = 9'b100100001
} state_e;
```
As reported in https://github.com/chipsalliance/Surelog/issues/3499 , Surelog doesn't evaluate the range in the definition of the enum.
The UHDM for the logic typespec of the enum we're getting here is:
```
logic_typespec: , line:5:16, endln:5:38
|vpiRange:
\_range: , line:5:22, endln:5:38
|vpiLeftRange:
\_operation: , line:5:23, endln:5:35
|vpiParent:
\_range: , line:5:22, endln:5:38
|vpiOpType:11
|vpiOperand:
\_ref_obj: (StateWidth), line:5:23, endln:5:33
|vpiParent:
\_operation: , line:5:23, endln:5:35
|vpiName:StateWidth
|vpiOperand:
\_constant: , line:5:34, endln:5:35
|vpiParent:
\_operation: , line:5:23, endln:5:35
|vpiDecompile:1
|vpiSize:64
|UINT:1 …
```
> Reduce expressions in logic typespecs

- systemverilog-plugin/third_party/yosys/simplify.cc
This PR adds support for simplifying structs and unions with a range.
It fixes a failure of ```Assert 'node->type == AST_STRUCT_ITEM' failed in frontends/ast/simplify.cc:319```, spotted before copying simplify from Yosys to the plugin codebase.
Added test for the fix: https://github.com/chipsalliance/UHDM-integration-tests/pull/721
Test yosys-systemverilog CI run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4629461693
> Support struct with a range in simplify

- systemverilog-plugin/tests/break_continue/break_continue.tcl
- systemverilog-plugin/tests/counter/counter.tcl
- systemverilog-plugin/tests/debug-flag/debug-flag.tcl
- systemverilog-plugin/tests/defaults/defaults.tcl
- systemverilog-plugin/tests/defines/defines.tcl
- systemverilog-plugin/tests/formal/formal.tcl
- systemverilog-plugin/tests/report-flag/report-flag.tcl
- systemverilog-plugin/tests/separate-compilation/separate-compilation.tcl
- systemverilog-plugin/tests/translate_off/translate_off.tcl
That probably was forgotten in the last change and it silently created files called ::env(...
> Tcl-tests: expand environment variables.

- systemverilog-plugin/UhdmAst.cc
Related to: https://github.com/chipsalliance/yosys-f4pga-plugins/issues/516
This PR fixes handling of unsized unbased constants.
Currently such constants are parsed as 32bits, but they should be parsed as 1bit.
UHDM-integration-test: https://github.com/chipsalliance/UHDM-integration-tests/pull/736
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/5000890738
> systemverilog-plugin: fix parsing unsized unbased consts

- systemverilog-plugin/UhdmAst.cc
Considering the fact that the name can consist of escaped characters, including dot, we need to change the way of stripping the name of a node - instead of a dot, we now use the ancestor name. 
Added test: https://github.com/chipsalliance/UHDM-integration-tests/pull/730 (It fails formal verification because of sv2v being unable to handle escaped characters, but is useful as a parsing test.)
Test yosys-systemverilog CI run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4916684728.
> sv-plugin: Strip the node name using parent name instead of "."

- systemverilog-plugin/UhdmAst.cc
I suggest reviewing this commit-by-commit.
Some leaks are still there, but everything exceps ASAN passes.
yosys-systemverilog (with ASAN checks): https://github.com/antmicro/yosys-systemverilog/actions/runs/5239038751
yosys-systemverilog (master): https://github.com/antmicro/yosys-systemverilog/actions/runs/5241954259
> systemverilog-plugin: Fix few ASAN issues

- systemverilog-plugin/UhdmAst.cc
- systemverilog-plugin/UhdmAst.h
- systemverilog-plugin/uhdmastshared.h
- systemverilog-plugin/uhdmsurelogastfrontend.cc
This PR adapts plugin code for recent Surelog version.
UHDM-integration-tests PR: https://github.com/chipsalliance/UHDM-integration-tests/pull/743
yosys-systemverilog CI: https://github.com/antmicro/yosys-systemverilog/actions/runs/5798599424
> systemverilog plugin: changes required for newer Surelog version

- Makefile
This is the last release with the SV plugin included.
> Bump plugins version
